/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import javax.swing.JOptionPane;
import com.michaelbaranov.microba.calendar.DatePicker; /*importacion de la libreria microba para el DatePicker*/
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Estudiante
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    DatePicker fechas1 = new DatePicker(new Date());
    DatePicker fechas2 = new DatePicker(new Date());
    DatePicker fechas3 = new DatePicker(new Date());
    DatePicker fechas4 = new DatePicker(new Date());
    list db = new list();

    public Menu() {
        initComponents();
        this.setLayout(null);
        JPanel d = new JPanel();
        JPanel de = new JPanel();
        JPanel dee = new JPanel();
        JPanel deee= new JPanel();
        deee.add(fechas4);
        dee.add(fechas3);
        de.add(fechas2);
        d.add(fechas1);
        Consultaji.add(d);
        Consultaji.add(de);
        Consultaji.add(dee);
        CrearCji.add(deee);
        fechas1.setVisible(true);
        fechas1.setSize(200, 200);
        fechas1.setFieldEditable(false);
        fechas2.setVisible(true);
        fechas3.setVisible(true);
        fechas3.setSize(200,200);
        fechas3.setEnabled(false);
        fechas2.setSize(200, 200);
        fechas2.setFieldEditable(false);
        Consultaji.setSize(370, 300);
        CrearCji.setSize(327,305);
        Consultaji.setResizable(false);
        this.setResizable(false);
        fechas4.setSize(200,200);
        fechas4.setFieldEditable(false);
        deee.setSize(100,40);
        deee.setLocation(100,120);
        d.setSize(100, 40);
        de.setSize(100, 40);
        d.setLocation(140, 95);
        de.setLocation(240, 95);
        dee.setLocation(140,140);
        dee.setSize(100,40);
        TextPrompt textoinfo = new TextPrompt("Num de cuenta",tf4); /*Clase creada por Rob Camick para usar placeholder*/ 
        TextPrompt textoinfo2 = new TextPrompt("Num de cuenta",tf5);
        Cancelacionji.setResizable(false);
        Cancelacionji.setSize(300,180);
        Cancelacionji.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consultaji = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cancelacionji = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        CrearCji = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numcuentatf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        montotf = new javax.swing.JTextField();
        crearcbt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        Consultaji.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton4.setText("a");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("b");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("c");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setText("Consulta");

        jLabel8.setText("Fecha Inicial:");

        jLabel9.setText("Fecha Final:");

        javax.swing.GroupLayout ConsultajiLayout = new javax.swing.GroupLayout(Consultaji.getContentPane());
        Consultaji.getContentPane().setLayout(ConsultajiLayout);
        ConsultajiLayout.setHorizontalGroup(
            ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultajiLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultajiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(45, 45, 45))
        );
        ConsultajiLayout.setVerticalGroup(
            ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(ConsultajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        Cancelacionji.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Cancelacionji.setPreferredSize(new java.awt.Dimension(300, 227));

        jButton7.setText("Cancelar cuenta");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setText("Cancelacion de cuenta");

        javax.swing.GroupLayout CancelacionjiLayout = new javax.swing.GroupLayout(Cancelacionji.getContentPane());
        Cancelacionji.getContentPane().setLayout(CancelacionjiLayout);
        CancelacionjiLayout.setHorizontalGroup(
            CancelacionjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelacionjiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CancelacionjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(CancelacionjiLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        CancelacionjiLayout.setVerticalGroup(
            CancelacionjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelacionjiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(CancelacionjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CrearCji.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel4.setText("Creacion de Cuenta");

        jLabel5.setText("Numero de cuenta:");

        jLabel6.setText("Fecha:");

        jLabel7.setText("Monto:");

        crearcbt.setText("Crear cuenta");
        crearcbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearCjiLayout = new javax.swing.GroupLayout(CrearCji.getContentPane());
        CrearCji.getContentPane().setLayout(CrearCjiLayout);
        CrearCjiLayout.setHorizontalGroup(
            CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCjiLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(CrearCjiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(montotf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(crearcbt)
                        .addGroup(CrearCjiLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(numcuentatf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearCjiLayout.setVerticalGroup(
            CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCjiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numcuentatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(CrearCjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(montotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(crearcbt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Consultas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelacion de la cuenta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Creacion de cuenta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel3.setText("Banco La Prosperidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        long monto = 0;
        Nodo aux = db.getptr();
            while (aux != null) {
                if ((aux.fecha.after(fechas1.getDate()) && aux.fecha.before(fechas2.getDate()))) {
                    if (aux.tipo==1) {
                        monto=monto+aux.monto;
                    }
                }
                aux=aux.Nazi;
            }
        JOptionPane.showMessageDialog(null, "El monto es de: " + monto);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        long monto = 0;
        Nodo aux = db.getptr();
            while (aux != null) {
                if (aux.fecha.before(fechas3.getDate())) {
                    if (aux.tipo==2) {
                        monto=monto+aux.monto;
                    }
                }
            }
        JOptionPane.showMessageDialog(null, "El retiro total es de: " + monto);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    long monto = 0;
        if (tf4 != null) {
            Nodo aux = db.getptr();
            while (aux != null) {
                if (aux.NroCta == Integer.parseInt(tf4.getText())) {
                    if (aux.tipo == 1) {
                        monto = monto + aux.monto;
                    }
                    if (aux.tipo == 2) {
                        monto = monto - aux.monto;
                    }
                }
                aux=aux.Nazi;
            }
        }
        JOptionPane.showMessageDialog(null, "El monto es de: " + monto);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Consultaji.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        long monto = 0;
        if (tf5 != null) {
            Nodo aux = db.getptr();
            while (aux != null) {
                if (aux.NroCta == Integer.parseInt(tf4.getText())) {
                    if (aux.tipo == 1) {
                        monto = monto + aux.monto;
                    }
                    if (aux.tipo == 2) {
                        monto = monto - aux.monto;
                    }
                }
                aux=aux.Nazi;
            }
            if (monto == 0) {
                db.delete(Integer.parseInt(tf4.getText()));
                JOptionPane.showMessageDialog(null,"Cuenta eliminada exitosamente!");
            }else JOptionPane.showMessageDialog(null,"Opcion no disponible para esta cuenta!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cancelacionji.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CrearCji.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void crearcbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcbtActionPerformed
       Nodo aux = db.getptr();
        int cuenta=Integer.parseInt(numcuentatf.getText());
        if (CrearCbuscar(aux, cuenta) && Integer.parseInt(montotf.getText())>=100000) {
            db.add(fechas4.getDate(),Long.parseLong(numcuentatf.getText()),Long.parseLong(montotf.getText()),1);
            JOptionPane.showMessageDialog(null,"Cuenta creada exitosamente!");
            numcuentatf.setText(null);
            montotf.setText(null);
        }
    }//GEN-LAST:event_crearcbtActionPerformed

    public boolean CrearCbuscar(Nodo aux, int numero){
        if (aux!=null) {
            if (aux.NroCta == Integer.parseInt(numcuentatf.getText())) {
                JOptionPane.showMessageDialog(null,"Cuenta ya existente!");
                return false;
            }else return CrearCbuscar(aux.Nazi,numero);
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Cancelacionji;
    private javax.swing.JDialog Consultaji;
    private javax.swing.JDialog CrearCji;
    private javax.swing.JButton crearcbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField montotf;
    private javax.swing.JTextField numcuentatf;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
